import type { Component } from 'vue';
import {
  Avatar,
  Bell,
  Calendar,
  ChatDotRound,
  CircleCheck,
  Clock,
  Collection,
  Connection,
  Cpu,
  CreditCard,
  DataAnalysis,
  DataLine,
  Delete,
  Document,
  Download,
  Edit,
  Files,
  Flag,
  Folder,
  FolderOpened,
  Goods,
  Grid,
  Guide,
  Histogram,
  HomeFilled,
  Key,
  Link,
  List,
  Location,
  Lock,
  Menu as MenuIcon,
  Message,
  MessageBox,
  Monitor,
  More,
  Notebook,
  OfficeBuilding,
  Phone,
  PieChart,
  Picture,
  Plus,
  PriceTag,
  Promotion,
  Reading,
  Refresh,
  Search,
  Setting,
  Share,
  Shop,
  Star,
  Suitcase,
  Tickets,
  Tools,
  Upload,
  User,
  UserFilled,
  Wallet,
} from '@element-plus/icons-vue';

/** 菜单图标可选项（菜单管理 icon 选择弹窗的数据源） */
export interface MenuIconOption {
  /** 存库的图标名（若依风格小写串） */
  name: string;
  component: Component;
}

/**
 * 菜单图标注册表：后端 sys_menu.icon 存这里的 name，
 * 前端统一映射到 @element-plus/icons-vue 组件，未登记的用 Menu 兜底。
 * 新增图标在此登记后，菜单管理的图标选择弹窗自动出现。
 */
export const MENU_ICON_OPTIONS: MenuIconOption[] = [
  { name: 'setting', component: Setting },
  { name: 'user', component: User },
  { name: 'peoples', component: UserFilled },
  { name: 'tree-table', component: Grid },
  { name: 'tree', component: OfficeBuilding },
  { name: 'dict', component: Collection },
  { name: 'tool', component: Suitcase },
  { name: 'tools', component: Tools },
  { name: 'edit', component: Edit },
  { name: 'avatar', component: Avatar },
  { name: 'menu', component: MenuIcon },
  { name: 'home', component: HomeFilled },
  { name: 'document', component: Document },
  { name: 'files', component: Files },
  { name: 'folder', component: Folder },
  { name: 'folder-open', component: FolderOpened },
  { name: 'bell', component: Bell },
  { name: 'message', component: Message },
  { name: 'message-box', component: MessageBox },
  { name: 'chat-dot', component: ChatDotRound },
  { name: 'promotion', component: Promotion },
  { name: 'monitor', component: Monitor },
  { name: 'lock', component: Lock },
  { name: 'key', component: Key },
  { name: 'search', component: Search },
  { name: 'calendar', component: Calendar },
  { name: 'clock', component: Clock },
  { name: 'data-analysis', component: DataAnalysis },
  { name: 'data-line', component: DataLine },
  { name: 'pie-chart', component: PieChart },
  { name: 'histogram', component: Histogram },
  { name: 'list', component: List },
  { name: 'tickets', component: Tickets },
  { name: 'notebook', component: Notebook },
  { name: 'reading', component: Reading },
  { name: 'star', component: Star },
  { name: 'flag', component: Flag },
  { name: 'tag', component: PriceTag },
  { name: 'link', component: Link },
  { name: 'connection', component: Connection },
  { name: 'share', component: Share },
  { name: 'download', component: Download },
  { name: 'upload', component: Upload },
  { name: 'refresh', component: Refresh },
  { name: 'circle-check', component: CircleCheck },
  { name: 'delete', component: Delete },
  { name: 'plus', component: Plus },
  { name: 'more', component: More },
  { name: 'location', component: Location },
  { name: 'guide', component: Guide },
  { name: 'phone', component: Phone },
  { name: 'credit-card', component: CreditCard },
  { name: 'wallet', component: Wallet },
  { name: 'shop', component: Shop },
  { name: 'goods', component: Goods },
  { name: 'cpu', component: Cpu },
  { name: 'picture', component: Picture },
];

const ICON_MAP: Record<string, Component> = Object.fromEntries(
  MENU_ICON_OPTIONS.map((o) => [o.name, o.component]),
);

export function menuIcon(name?: string): Component {
  return (name && ICON_MAP[name]) || MenuIcon;
}
